todo/urls.py
from django.contrib import admin
from django.urls import path
from todo.views import todolist_view, addlist_view, delete_view, edit_view

app_name = "todo"

urlpatterns = [

    path('', todolist_view, name="todolist_view"),
    path('addlist_view/', addlist_view, name="addlist_view"),
    path('delete_view/<int:task_id>/', delete_view, name="delete_view"),
    path('edit_view/<int:task_id>/', edit_view, name="edit_view"),


]

todolist/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import authenticate, login
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("todo.urls", namespace="todo")),
    path('users/', include("users.urls", namespace="users")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import signup,login_view,logout_view
from django.contrib.auth import views as auth_views
from django.conf.urls import url

app_name =  'users'
urlpatterns = [
path('signup/',signup, name="signup"),
path('login_view/',login_view, name="login_view"),
path('logout_view/',logout_view, name="logout_view"),
]

todo/models.py
from django.db import models
from django.utils.html import format_html
from django.contrib.auth import get_user_model
from django.conf import settings
from django.contrib.auth.models import User



class Task(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.TextField(null = True, blank = True)
    date = models.DateField(auto_now = False, auto_now_add = False)
    Priority = (("low", "low"), ("medium" ,"medium"), ("high" ,"high"))
    priority = models.CharField(max_length=255, blank=True, null=True, choices=Priority)
    


    def __str__(self):
        return self.title

    

# Create your models here.

users/models.py
from django.db import models

# Create your models here.

todo/forms.py
from django import forms
from todo.models import Task 

class TaskForm(forms.ModelForm):
	class Meta:
		model = Task
		fields = ("title", "description", "date","priority")

users/forms.py
from django import forms
from todo.models import Task
from django.contrib.auth.forms import UserCreationForm, User


class SignupForm(UserCreationForm):

    class Meta:
        model = User
        fields = ("username", "password1", "password2")

todo/views.py
from django.shortcuts import render, redirect, reverse
from todo.models import Task
from django.http import HttpResponse, HttpResponseRedirect
from datetime import datetime
from django.contrib.auth.forms import UserCreationForm
from todo.forms import TaskForm
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required


@login_required(login_url="/users/login_view/")
def todolist_view(request):
    today = datetime.now().date()
    todolist = Task.objects.filter(user=request.user)
    # user = User.objects.all()
    context = {"todolist": todolist, "today": today}
    return render(request, "todolist.html", context)


@login_required(login_url="/users/login_view/")
def addlist_view(request):
    form = TaskForm(request.POST or None)
    if form.is_valid():
        Task = form.save(commit=False)
        Task.user = request.user
        Task = Task.save()
        # form.save()
        # return HttpResponseRedirect()
        return redirect(reverse("todo:todolist_view"))
    else:
        form = TaskForm()
    return render(request, "form.html", {"form": form})


def delete_view(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    task.delete()
    return redirect(reverse("todo:todolist_view"))


@login_required(login_url="/users/login_view/")
def edit_view(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    form = TaskForm(request.POST or None, instance=task)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse("todo:todolist_view"))
    return render(request, "form.html", {"form": form})

users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from django.http import HttpResponse
from users.forms import SignupForm


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect(reverse("todo:todolist_view"))
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})


def login_view(request):
    if request.method == 'GET':
        context = ''
        return render(request, 'registration/login.html', {'context': context})
    elif request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(reverse("todo:todolist_view"))

        else:
            error = "Invalid Credentials!"
            context = {"error": error}
            return render(request, 'registration/login.html', context)


def logout_view(request):
    logout(request)
    return redirect(reverse("users:login_view"))

todo/templates/base.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href ="{%static 'users/style.css' %}">
</head>
<body  class="backg">
    <hr>
   

<hr>
    <div class ="loginBox">
        <div class="card">
            <div class ="text-center text-info"><h4>To do List App</h4> </div><hr>
            <div class="padding">
                {% block content %}
      
                {% endblock %}
            </div>
        </div>
        
    </div>

   
            
</body>

</html>

todo/templates/form.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<link rel="stylesheet" href ="{%static 'todo/style.css' %}">
	<link rel="stylesheet" href ="{%static 'users/style.css' %}">
</head>
<body class="backg">
	<div class="card mb-5 m-5">
		<form method="POST" action="" enctype="multipart/form-data">
			{% csrf_token %}
			<div class="form-padding">
				<label>{{form.title.label}}<br>
					{{form.title}}</label><br>
					<label>{{form.description.label}}<br>
						{{form.description}}</label><br>
						<label>{{form.date.label}}<br>
							{{form.date}}</label><br>
							<label>{{form.priority.label}}<br>
								{{form.priority}}</label><br>  
			
			
				
			<input class="btn btn-info" type="submit" value="Submit"/>
		</div>
			
			
		</form>
	</div>
</body>
</html>

todo/templates/todolist.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href ="{%static 'users/style.css' %}">
        <title>Todo List</title>
    </head>
    <hr>
    <body class="container"> 
        
        <div class="btn"> Today is {{today}} </div>
        <a class="btn btn-info float-right" href="/users/logout_view">logout</a> 
        <a  class="btn btn-success" href="/addlist_view">Add Task List</a> 
        <hr>
             
            <div class ="row">
                {% for e in todolist %}   
                    {% if e.priority == "high" %}
                    <div class="col-sm-4">
                        <div class ="card text-black bg-success mb-4">
                            <p class="card-header"><bold>Title: {{e.title}}</bold></p>
                            <div class="card-body">
                                <p>Description: {{e.description}}</p>
                                <p>Date: {{e.date}}</p>
                                <p>User: {{request.user}}</p>
                                <p>Priority: {{e.priority}}</p>
                                <a button type="button" class="btn btn-dark" href="{% url 'todo:delete_view' e.id %}">Delete</button></a>
                                <a button type="button" class="btn btn-dark" href="{% url 'todo:edit_view' e.id %}">Edit</button></a>           
                            </div>
                        </div>                  
                    </div>    
                       
                
                    {% elif e.date < today %}
                    <div class="col-sm-4 mb-4">
                        <div class= "card text-black bg-warning">   
                            <p class="card-header">Title: {{e.title}}</p>
                            <div class="card-body">
                                <p>Description: {{e.description}}</p>
                                <p>Date: {{e.date}}</p>
                                <p>User: {{request.user}}</p>
                                <p>Priority: {{e.priority}}</p>
                                <a button type="button" class="btn btn-dark" href="{% url 'todo:delete_view' e.id %}">Delete</button></a>
                                <a button type="button" class="btn btn-dark" href="{% url 'todo:edit_view' e.id %}">Edit</button></a>                       
                            </div> 
                        </div>
                    </div>
                            

               
                    {% else %}
                    <div class="col-sm-4">   
                        <div class ="card text-black bg-light mb-4">
                            <p class="card-header">Title: {{e.title}}</p>
                            <div class="card-body">
                                <p>Description: {{e.description}}</p>
                                <p>Date: {{e.date}}</p>
                                <p>User: {{request.user}}</p>
                                <p>Priority: {{e.priority}}</p>
                                <a button type="button" class="btn btn-dark" href="{% url 'todo:delete_view' e.id %}">Delete</button></a>
                                <a button type="button" class="btn btn-dark" href="{% url 'todo:edit_view' e.id %}">Edit</button></a>
                            </div>
                        </div>    
                    </div>


                    
                    

                    {% endif %}
                    {% endfor %}        
                
            </div>   
         
       
        

    </body>

</html>